---
version: 2
plan:
  project-key: MAC
  key: SFM
  name: Sentry-Cocoa for Mac
  description: Clone of sentry-cocoa to build a static framework for Mac
stages:
  - Build Stage:
      manual: false
      final: false
      jobs:
        - Build Job

Build Job:
  key: JOB1
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script: |
        bamboo-specs/scripts/setup_ssh.sh
    - script:
      description: Build. Upload to artifactory if in the master branch.
      scripts:
        - bamboo-specs/scripts/build.sh
  artifacts:
    - name: Sentry.xcframework.zip
      location: Carthage
      pattern: Sentry.xcframework.zip
      shared: true
      required: true
  requirements:
    - ephemeral
    - image: registry.int.agrd.dev/macos/sequoia-build-agent-xcode16.1:latest
repositories:
  - mac-sentry-cocoa:
      scope: global
branches:
  create: for-pull-request
  delete:
    after-deleted-days: 1
    after-inactive-days: 30
  link-to-jira: true
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
...
